---
title: The Physics Blog
date: 2020-08-23
---
author: Kartik Kakade
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site about physics topics tauf=ght at college level

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
